### ISSUE TITLE
Style Typeahead Results And Inputs

### ISSUE THREAD

**Issue by brenthaertlein** [staticsound/moviechallenge#31]
Issue created.

**Comment by brenthaertlein** [comment]
### Description

Various things.

**Comment by brenthaertlein** [comment]
### Sub-tasks
- [ ] Dynamic font sizes and two-line input
- [x] If both inputs are empty, challenge becomes re-editable (?)
- [x] .search div overlaps .challenge div
